INSERT INTO subscription_plans (
    plan_type,
    plan_display_name,
    max_watchlist,
    signal_delay_hours,
    journal_max_entries,
    has_alt_data,
    has_detail_report,
    has_backtesting,
    price_monthly,
    price_yearly
) VALUES
    (
        'free',
        'Free',
        3,
        24,
        50,
        FALSE,
        FALSE,
        FALSE,
        0,
        0
    ),
    (
        'pro',
        'Pro',
        20,
        3,
        300,
        TRUE,
        TRUE,
        FALSE,
        9900,
        99000
    ),
    (
        'premium',
        'Premium',
        100,
        0,
        1000,
        TRUE,
        TRUE,
        TRUE,
        19900,
        199000
    )
ON CONFLICT (plan_type) DO NOTHING;
