-- 20260707_1500_community_board.sql
-- target: backend
-- ============================================================================
-- 저널 커뮤니티 게시판 — 공개 공유 레이어 (spec: docs/spec/journal-board-spec.md)
-- ----------------------------------------------------------------------------
-- 배경: signal_journals 는 owner 전용·구독 전용(비공개)이고 visibility 컬럼이 없다.
--   "공유"는 저널을 공개로 뒤집는 게 아니라, 유저가 올린 것만 공개되는 별도 레이어다
--   (프라이버시 by design). community_posts 가 저널 항목을 라이브 참조(journal_id)하며,
--   공개 응답은 화이트리스트 컬럼(stock/user_view/user_memo)만 노출한다 — 가격·절대손익·
--   PII 는 애플리케이션 라우트에서 명시 투영으로 제외한다(NFR-1). 수익률%는 작성자가
--   show_pnl 을 켠 게시글에서만 노출.
-- 설계: 읽기 전체 공개(비로그인 포함) / 쓰기 로그인. 반응·조회·신고는 unique 로 어뷰징
--   방지. 랭킹은 워커 배치가 community_post_rankings 에 멱등 upsert(가중합, 롤링 7일) —
--   signal_journal_outcomes 와 같은 워커→백엔드 계약. 모더레이션은 신고 임계 자동숨김
--   (status='hidden') + 관리자 검토.
-- 분류: 6개 테이블 전부 backend DB(users/signal_journals 와 공존, db_partition.py 등록).
-- 의존 순서: community_posts → (comments, reactions, post_views, reports, post_rankings).
-- ============================================================================

-- 1) 게시글 -----------------------------------------------------------------
CREATE TABLE public.community_posts (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_user_id  bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    -- 저널 항목 라이브 참조. 원본 저널 삭제 시 참조만 끊고 게시글은 남긴다(NULL, "원본 없음").
    journal_id      bigint REFERENCES public.signal_journals(id) ON DELETE SET NULL,
    title           varchar(200) NOT NULL,
    body            text NOT NULL DEFAULT '',
    -- 작성자 opt-in: 켜면 수익률%(outcome change_pct)만 노출. 절대금액·가격은 항상 제외.
    show_pnl        boolean NOT NULL DEFAULT false,
    view_count      integer NOT NULL DEFAULT 0,
    -- 모더레이션: 신고 임계 도달 or 관리자 조치 시 'hidden'. 피드에서 제외.
    status          varchar(10) NOT NULL DEFAULT 'visible',
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz,
    CONSTRAINT chk_community_post_status CHECK (status IN ('visible', 'hidden'))
);

CREATE INDEX idx_community_posts_feed
    ON public.community_posts (created_at DESC, id DESC)
    WHERE deleted_at IS NULL AND status = 'visible';
CREATE INDEX idx_community_posts_author
    ON public.community_posts (author_user_id);
CREATE INDEX idx_community_posts_journal
    ON public.community_posts (journal_id);

CREATE TRIGGER trg_community_posts_updated_at
    BEFORE UPDATE ON public.community_posts
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- 2) 댓글 / 1단계 대댓글 -----------------------------------------------------
-- parent_comment_id 는 1레벨만 허용(대댓글에 대댓글 불가) — 앱단에서 강제.
CREATE TABLE public.community_comments (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id            bigint NOT NULL REFERENCES public.community_posts(id) ON DELETE CASCADE,
    parent_comment_id  bigint REFERENCES public.community_comments(id) ON DELETE CASCADE,
    author_user_id     bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    body               text NOT NULL,
    status             varchar(10) NOT NULL DEFAULT 'visible',
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    deleted_at         timestamptz,
    CONSTRAINT chk_community_comment_status CHECK (status IN ('visible', 'hidden'))
);

CREATE INDEX idx_community_comments_post
    ON public.community_comments (post_id, created_at);
CREATE INDEX idx_community_comments_parent
    ON public.community_comments (parent_comment_id);

CREATE TRIGGER trg_community_comments_updated_at
    BEFORE UPDATE ON public.community_comments
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- 3) 반응(좋아요·북마크) -----------------------------------------------------
-- 폴리모픽 타깃(post/comment). target_id 는 앱단 정합(FK 아님). 유저·타깃·타입당 1회.
CREATE TABLE public.community_reactions (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    target_type  varchar(10) NOT NULL,
    target_id    bigint NOT NULL,
    type         varchar(10) NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_community_reaction_target CHECK (target_type IN ('post', 'comment')),
    CONSTRAINT chk_community_reaction_type CHECK (type IN ('like', 'bookmark')),
    CONSTRAINT uq_community_reaction UNIQUE (user_id, target_type, target_id, type)
);

CREATE INDEX idx_community_reactions_target
    ON public.community_reactions (target_type, target_id, type);

-- 4) 조회 중복방지 -----------------------------------------------------------
-- 유저(또는 세션 해시)·게시글·날짜당 1회. 삽입 성공 시에만 posts.view_count 증가(앱단).
CREATE TABLE public.community_post_views (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     bigint NOT NULL REFERENCES public.community_posts(id) ON DELETE CASCADE,
    viewer_key  varchar(64) NOT NULL,
    viewed_on   date NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_community_post_view UNIQUE (post_id, viewer_key, viewed_on)
);

-- 5) 신고 -------------------------------------------------------------------
-- 유저·타깃당 1회(중복신고 방지). 서로 다른 신고자 집계 ≥ 임계 → 대상 status='hidden'.
CREATE TABLE public.community_reports (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id  bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    target_type       varchar(10) NOT NULL,
    target_id         bigint NOT NULL,
    reason            varchar(30),
    created_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_community_report_target CHECK (target_type IN ('post', 'comment')),
    CONSTRAINT uq_community_report UNIQUE (reporter_user_id, target_type, target_id)
);

CREATE INDEX idx_community_reports_target
    ON public.community_reports (target_type, target_id);

-- 6) 인기 랭킹 스냅샷 --------------------------------------------------------
-- 워커 배치가 가중합 점수를 멱등 upsert. window_kind: 'weekly'(롤링 7일) / 'all'.
-- (window 은 PostgreSQL 예약어라 컬럼명으로 못 쓴다 → window_kind.)
CREATE TABLE public.community_post_rankings (
    post_id      bigint NOT NULL REFERENCES public.community_posts(id) ON DELETE CASCADE,
    window_kind  varchar(10) NOT NULL,
    score        numeric(12,3) NOT NULL DEFAULT 0,
    likes        integer NOT NULL DEFAULT 0,
    comments     integer NOT NULL DEFAULT 0,
    views        integer NOT NULL DEFAULT 0,
    computed_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_community_post_rankings PRIMARY KEY (post_id, window_kind),
    CONSTRAINT chk_community_ranking_window CHECK (window_kind IN ('weekly', 'all'))
);

CREATE INDEX idx_community_rankings_board
    ON public.community_post_rankings (window_kind, score DESC, post_id DESC);

-- Grants (멱등, 롤 존재 시에만) --------------------------------------------
--   signal_backend : API 가 게시판 CRUD/피드/신고 서빙 — 읽기·쓰기.
--     community_post_rankings 는 읽기 전용(워커가 계산). signal_journals 화이트리스트
--     조인은 backend 가 이미 SELECT 권한 보유(owner 저널 기능) → 추가 grant 불요, 노출
--     제한은 라우트 명시 투영으로 강제.
--   signal_worker  : 랭킹 배치가 집계 소스 읽고(post/comment/reaction/view) 랭킹 upsert.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_backend') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON
            public.community_posts,
            public.community_comments,
            public.community_reactions,
            public.community_post_views,
            public.community_reports
            TO signal_backend;
        GRANT SELECT ON public.community_post_rankings TO signal_backend;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_worker') THEN
        GRANT SELECT ON
            public.community_posts,
            public.community_comments,
            public.community_reactions,
            public.community_post_views
            TO signal_worker;
        GRANT SELECT, INSERT, UPDATE, DELETE ON public.community_post_rankings TO signal_worker;
    END IF;
END $$;
