-- 20260707_1900_user_trade_signal_overlays.sql
-- target: backend
-- ============================================================================
-- 매매 의사결정 부검 — PIT 관측신호 오버레이 (spec: journal-postmortem-spec.md §3, FR-5)
-- ----------------------------------------------------------------------------
-- 유저가 거래한 종목·기간에 "그 시점 실제로 관측 가능했던(PIT-safe) 신호"를 겹쳐 3분류
--   판정의 근거로 쓴다. 워커가 수집 DB(dart_ownership_events, report_date=known_at)를 읽어
--   유저 거래 구간의 신호를 backend 로 멱등 적재한다(저널 outcome 워커와 같은 이중풀 계약).
--   **사후확신 금지**: report_date(공시 접수일) 이하 = 관측 가능 시점만. 사후 고점/저점 미사용.
-- 분류: backend DB(유저 콘텐츠). 워커 RW(갱신), backend 는 부검 조회 SELECT.
-- MVP 소스 = 내부자/최대주주 공시(dart_ownership). 검색트렌드(datalab)·시세(ohlcv 급락/거래량)
--   오버레이는 후속 증분.
-- ============================================================================

CREATE TABLE public.user_trade_signal_overlays (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    stock_id    bigint NOT NULL REFERENCES public.stocks(id) ON DELETE CASCADE,
    ticker      varchar(20) NOT NULL,
    -- 관측 가능 시점(PIT). dart_ownership.report_date(공시 접수일)=known_at.
    signal_date date NOT NULL,
    kind        varchar(20) NOT NULL,
    -- 공시 단위 식별자(rcept_no:line_seq). 같은 날 서로 다른 내부자 공시가 한 행으로
    -- collapse 되지 않도록 자연키에 포함한다(count 과소집계·detail 덮어씀 방지).
    source_ref  varchar(40) NOT NULL DEFAULT '',
    detail      jsonb NOT NULL DEFAULT '{}',
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_overlay_kind CHECK (kind IN ('insider_sell', 'insider_buy')),
    CONSTRAINT uq_trade_overlay UNIQUE (user_id, stock_id, signal_date, kind, source_ref)
);

CREATE INDEX idx_overlay_user_stock
    ON public.user_trade_signal_overlays (user_id, stock_id, signal_date);

-- Grants (멱등, 롤 존재 시에만) --------------------------------------------
--   signal_worker  : 오버레이 갱신 워커가 적재/재계산(INSERT·SELECT·DELETE).
--   signal_backend : 부검 조회(SELECT).
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_worker') THEN
        GRANT SELECT, INSERT, DELETE ON public.user_trade_signal_overlays TO signal_worker;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_backend') THEN
        GRANT SELECT ON public.user_trade_signal_overlays TO signal_backend;
    END IF;
END $$;
