-- 20260701_1200_collection_schedule_runs.sql
-- target: backend
-- ============================================================================
-- Scheduler execution history. The scheduler writes one row per fired run so
-- operators can inspect per-run trigger reason, targets, status, and detail.
-- ============================================================================

CREATE TABLE public.collection_schedule_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id bigint REFERENCES public.collection_schedules(id) ON DELETE SET NULL,
    schedule_name varchar(64) NOT NULL,
    trigger_reason text NOT NULL,
    targets jsonb NOT NULL DEFAULT '[]'::jsonb,
    status text NOT NULL DEFAULT 'running',
    detail jsonb,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_collection_schedule_runs_schedule_started
    ON public.collection_schedule_runs (schedule_id, started_at DESC);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_backend') THEN
        GRANT SELECT ON public.collection_schedule_runs TO signal_backend;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_worker') THEN
        GRANT SELECT, INSERT, UPDATE ON public.collection_schedule_runs TO signal_worker;
    END IF;
END $$;
