-- 20260703_2035_guard_kill_switch.sql
-- target: backend
-- ============================================================================
-- 지정학 리스크 Kill-Switch (guard_*) 테이블
-- ----------------------------------------------------------------------------
-- 배경: 전쟁·휴전 등 지정학 충격 구간에서는 신호가 현실과 어긋날 수 있어,
--   리포트 "노출"을 일시 차단하는 fail-safe 스위치가 필요하다. 차단 상태의
--   단일 진실원천은 guard_site_status 싱글턴 1행이며, main-server 공개 API
--   (GET /api/guard/status)와 프론트 게이트가 이 값을 읽는다. 생성/발행
--   파이프라인은 건드리지 않는다(노출 차단만 — 무조건 발행 결정 유지).
-- 설계: 관리자 수동 토글(안전 핵심 경로)은 워커 없이 동작해야 하므로 backend
--   소유로 둔다. 워커측 뉴스 감시 에이전트는 BACKEND_DATABASE_URL 풀로 판정
--   이력(guard_news_events)·차단 제안(guard_recommendations)을 적재하고
--   auto 모드에서만 guard_site_status 를 갱신한다(signal_journal_outcomes 의
--   워커→백엔드 계약 선례). 모든 상태 변경은 guard_status_audit 에 남긴다
--   (에이전트도 actor 가 되므로 admin_audit_log 와 분리).
-- ============================================================================

-- 차단 스위치(싱글턴 1행) = 단일 진실원천
CREATE TABLE public.guard_site_status (
    id           smallint PRIMARY KEY DEFAULT 1,
    status       varchar(20) NOT NULL DEFAULT 'ok',
    scope        varchar(30) NOT NULL DEFAULT 'report_generation',
    mode         varchar(20) NOT NULL DEFAULT 'advisory',
    reason       text,
    resume_at    timestamptz,
    triggered_by varchar(100),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT guard_site_status_singleton CHECK (id = 1),
    CONSTRAINT chk_guard_status CHECK (status IN ('ok', 'blocked')),
    CONSTRAINT chk_guard_scope CHECK (scope IN ('report_generation', 'report_view', 'whole_site')),
    CONSTRAINT chk_guard_mode CHECK (mode IN ('manual', 'advisory', 'auto'))
);

-- 싱글턴 행은 스키마의 일부(시드 데이터가 아님) — 항상 존재해야 API 가 읽는다.
INSERT INTO public.guard_site_status (id) VALUES (1) ON CONFLICT DO NOTHING;

-- 수집·판정한 뉴스 이력(워커 에이전트가 적재)
CREATE TABLE public.guard_news_events (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source               varchar(20) NOT NULL,
    article_hash         varchar(64) NOT NULL UNIQUE,
    title                text,
    url                  text,
    published_at         timestamptz,
    severity             smallint,
    is_geopolitical_risk boolean,
    direction            varchar(20),
    summary              text,
    regions              text[],
    affected_themes      text[],
    confidence           smallint,
    prompt_version       varchar(40),
    judged_at            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_guard_news_direction
        CHECK (direction IS NULL OR direction IN ('escalation', 'deescalation', 'unclear'))
);

CREATE INDEX idx_guard_news_events_judged_at ON public.guard_news_events (judged_at DESC);

-- 차단 제안(advisory 모드: 에이전트 제안 → 관리자 승인/거절)
CREATE TABLE public.guard_recommendations (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_event_id   bigint REFERENCES public.guard_news_events(id) ON DELETE SET NULL,
    suggested_scope varchar(30) NOT NULL,
    severity        smallint,
    reason          text,
    status          varchar(20) NOT NULL DEFAULT 'pending',
    decided_by      varchar(100),
    decided_at      timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_guard_reco_scope
        CHECK (suggested_scope IN ('report_generation', 'report_view', 'whole_site')),
    CONSTRAINT chk_guard_reco_status CHECK (status IN ('pending', 'approved', 'rejected'))
);

CREATE INDEX idx_guard_recommendations_status ON public.guard_recommendations (status, created_at DESC);

-- 상태 변경 감사 로그(관리자·에이전트 공통 actor)
CREATE TABLE public.guard_status_audit (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action     varchar(20) NOT NULL,
    scope      varchar(30),
    reason     text,
    actor      varchar(100),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_guard_status_audit_created ON public.guard_status_audit (created_at DESC);

-- Grants (멱등, 롤 존재 시에만):
--   signal_backend : 공개 status 조회 + 관리자 토글/승인 (guard 전 테이블 읽기·쓰기).
--   signal_worker  : 뉴스 이력·제안 적재, auto 모드의 상태 갱신, 감사 기록.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_backend') THEN
        GRANT SELECT, INSERT, UPDATE ON public.guard_site_status TO signal_backend;
        GRANT SELECT, INSERT, UPDATE ON public.guard_news_events TO signal_backend;
        GRANT SELECT, INSERT, UPDATE ON public.guard_recommendations TO signal_backend;
        GRANT SELECT, INSERT ON public.guard_status_audit TO signal_backend;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_worker') THEN
        GRANT SELECT, UPDATE ON public.guard_site_status TO signal_worker;
        GRANT SELECT, INSERT ON public.guard_news_events TO signal_worker;
        GRANT SELECT, INSERT, UPDATE ON public.guard_recommendations TO signal_worker;
        GRANT SELECT, INSERT ON public.guard_status_audit TO signal_worker;
    END IF;
END $$;
