-- 20260707_1700_user_trade_fills.sql
-- target: backend
-- ============================================================================
-- 매매 의사결정 부검 — 유저 체결내역(trade fills) (spec: journal-postmortem-spec.md §3.3)
-- ----------------------------------------------------------------------------
-- 유저 증권사 계좌에서 조회한 실매매 체결(매수/매도 일자·수량·가격)을 공통 스키마로 정규화해
--   담는다. 워커 동기화 러너가 브로커 API(키움/토스)에서 증분 조회 → ticker→stock_id 매핑 →
--   (user_id, broker, broker_fill_id) 자연키로 멱등 upsert(NFR-3). 체결은 불변이라 갱신 없음
--   (updated_at 없음). 부검(단건/패턴)은 이 테이블을 라운드트립으로 묶어 계산한다.
-- ticker 매핑 실패(비상장/해외)면 stock_id NULL·ticker 보존(overlay만 제한, 체결은 유지).
-- 분류: backend DB(자격증명·저널과 공존). 워커가 INSERT, backend가 부검 조회 SELECT + 유저
--   데이터 삭제 DELETE. stocks(PUBLISHED, 양쪽 DB)로 종목 매핑.
-- ============================================================================

CREATE TABLE public.user_trade_fills (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    broker          varchar(10) NOT NULL,
    account_ref     varchar(64) NOT NULL DEFAULT '',
    -- 브로커 체결 고유 식별자(주문id+체결seq 등). 멱등 재동기화의 자연키.
    broker_fill_id  varchar(80) NOT NULL,
    -- 매핑 실패 시 NULL(원본 종목 삭제/비상장/해외). ticker 는 항상 보존.
    stock_id        bigint REFERENCES public.stocks(id) ON DELETE SET NULL,
    ticker          varchar(20) NOT NULL,
    side            varchar(4) NOT NULL,
    filled_at       timestamptz NOT NULL,
    quantity        numeric(18, 4) NOT NULL,
    price           numeric(18, 4) NOT NULL,
    fee             numeric(18, 4),
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_trade_fill_broker CHECK (broker IN ('kiwoom', 'toss')),
    CONSTRAINT chk_trade_fill_side CHECK (side IN ('buy', 'sell')),
    CONSTRAINT chk_trade_fill_qty CHECK (quantity > 0),
    CONSTRAINT uq_trade_fill UNIQUE (user_id, broker, broker_fill_id)
);

-- 부검 단건(종목별 라운드트립) 조회.
CREATE INDEX idx_trade_fills_user_stock ON public.user_trade_fills (user_id, stock_id, filled_at);
-- 증분 커서(브로커별 마지막 체결) + 패턴 부검(전체 시간순).
CREATE INDEX idx_trade_fills_user_broker ON public.user_trade_fills (user_id, broker, filled_at DESC);

-- 온디맨드 동기화 신호 ------------------------------------------------------
-- main-server 는 워커 코드를 직접 호출할 수 없다(서비스 분리) → 유저가 "동기화"를 누르면
-- backend 가 sync_requested_at 을 찍고, 워커 러너(잦은 크론)가 이 값이 찍힌/오래된
-- 자격증명을 우선 처리한 뒤 비운다. 온디맨드+주기 증분(결정)을 플래그로 잇는다.
ALTER TABLE public.user_broker_credentials
    ADD COLUMN sync_requested_at timestamptz;

-- Grants (멱등, 롤 존재 시에만) --------------------------------------------
--   signal_worker  : 동기화 러너가 체결 적재(INSERT) + 증분 커서 조회(SELECT).
--   signal_backend : 부검 조회(SELECT) + 유저 데이터 삭제(DELETE, 연동해제 후 정리).
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_worker') THEN
        GRANT SELECT, INSERT ON public.user_trade_fills TO signal_worker;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_backend') THEN
        GRANT SELECT, DELETE ON public.user_trade_fills TO signal_backend;
    END IF;
END $$;
