-- 20260707_1800_user_trade_plans.sql
-- target: backend
-- ============================================================================
-- 매매 의사결정 부검 — 유저 매매 계획(선택 입력) (spec: journal-postmortem-spec.md §3.3, FR-4)
-- ----------------------------------------------------------------------------
-- 유저가 매수 시점에 세운 계획(thesis·목표가·손절가·매도조건). Plan vs Actual 부검의
--   기준선 — 있으면 라운드트립을 유저 자기 규칙과 대조하고, 없으면 "놓칠 수밖에 없는 구조"로
--   안내한다(선택 입력, FR-4). 예측·사후확신 0 — 순수 유저 규칙 대비.
-- 종목당 1개(최신 계획, upsert). 재진입 시 갱신. stocks(PUBLISHED) 매핑, 미상장은 stock_id NULL.
-- 분류: backend DB(유저 콘텐츠, users 와 공존).
-- ============================================================================

CREATE TABLE public.user_trade_plans (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    stock_id       bigint REFERENCES public.stocks(id) ON DELETE SET NULL,
    ticker         varchar(20) NOT NULL,
    thesis         text NOT NULL DEFAULT '',
    target_price   numeric(18, 4),
    stop_price     numeric(18, 4),
    sell_condition text,
    planned_at     timestamptz NOT NULL DEFAULT now(),
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_trade_plan UNIQUE (user_id, ticker)
);

CREATE INDEX idx_trade_plans_user ON public.user_trade_plans (user_id);

CREATE TRIGGER trg_trade_plans_updated_at
    BEFORE UPDATE ON public.user_trade_plans
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- Grants (멱등, 롤 존재 시에만) --------------------------------------------
--   signal_backend : 계획 CRUD + 부검 조회(RW). 워커는 계획을 만들지 않는다(유저 입력).
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_backend') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_trade_plans TO signal_backend;
    END IF;
END $$;
