-- 20260707_1336_stock_news_per_ticker.sql
-- target: backend
-- ============================================================================
-- 종목별 뉴스(stock_news) 테이블 — 토스식 종목 뉴스 목록/건수 데이터 공급원
-- ----------------------------------------------------------------------------
-- 배경: 메인 페이지 토스 오마주에서 종목별 실제 뉴스(제목·링크·시각)를 보여주려
--   하나, 우리 데이터 모델엔 종목 뉴스가 없다(소스=DART/주가/채용/특허/데이터랩/
--   증권사리포트). 네이버 뉴스 검색 API 로 종목별 뉴스를 수집·저장한다.
-- 설계: guard_news_events 선례를 그대로 미러링한다 — 워커 뉴스 데몬이
--   BACKEND_DATABASE_URL 풀로 직접 적재하고, main-server 는 api.stock_news 뷰로
--   읽는다(2-DB 물리분리 #531: main-server 는 백엔드 DB 만 접속). 점수·시그널
--   파이프라인과 무관한 display-only 컨텍스트 레이어라 signal_events/scoring 은
--   건드리지 않는다. cross-DB FK 불가 원칙에 따라 stocks 로의 하드 FK 없이
--   stock_id + ticker 를 비정규화 저장한다(guard 와 동일 철학).
--   멱등 적재 키 = (stock_id, article_hash), article_hash = sha256(url or title).
-- ============================================================================

CREATE TABLE public.stock_news (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id     bigint NOT NULL,
    ticker       varchar(10) NOT NULL,
    article_hash varchar(64) NOT NULL,
    title        text NOT NULL,
    summary      text,
    url          text,
    press        varchar(120),
    source       varchar(20) NOT NULL DEFAULT 'NAVER_NEWS',
    published_at timestamptz,
    collected_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT stock_news_uniq UNIQUE (stock_id, article_hash)
);

-- 종목별 최신 뉴스 조회(목록/건수) 및 데몬의 "due" 판정(MAX(collected_at)) 용.
CREATE INDEX idx_stock_news_stock_published ON public.stock_news (stock_id, published_at DESC NULLS LAST);
CREATE INDEX idx_stock_news_stock_collected ON public.stock_news (stock_id, collected_at DESC);

-- main-server 읽기 계약 — base 권한 없이 뷰로만 조회(소유자 권한 실행, 0005 선례).
CREATE OR REPLACE VIEW api.stock_news AS
SELECT
    stock_id,
    ticker AS stock_code,
    title,
    summary,
    url,
    press,
    source,
    published_at,
    collected_at
FROM public.stock_news;

-- Grants (멱등, 롤 존재 시에만):
--   signal_worker  : 뉴스 데몬이 stocks(due 판정) 읽고 stock_news 적재.
--   signal_backend : main-server 가 api.stock_news 뷰로 목록/건수 조회.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_worker') THEN
        GRANT SELECT ON public.stocks TO signal_worker;
        GRANT SELECT, INSERT ON public.stock_news TO signal_worker;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_backend') THEN
        GRANT SELECT ON api.stock_news TO signal_backend;
    END IF;
END $$;
