-- 20260629_0900_collection_schedules.sql
-- target: backend
-- ============================================================================
-- 수집 스케줄 제어 평면 (config + 상태). 백엔드 DB 에만 적용.
-- ----------------------------------------------------------------------------
-- 배경: 어드민/MCP 는 main-server(백엔드 DB, signal_backend)에서 이 테이블을 읽고/쓰고,
--   워커측 스케줄러(run_scheduler_instance)는 발행용 백엔드 연결(BACKEND_DATABASE_URL)로
--   이 행을 폴링해 매일 run_at_local(KST) 에 수집을 트리거하고 실행 상태를 다시 기록한다.
--   cross-DB FK 없음 — 단일 config 행으로 제어(main-server → worker 직접 호출 없음).
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.collection_schedules (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                        varchar(64) NOT NULL UNIQUE,
    enabled                     boolean NOT NULL DEFAULT true,
    -- 로컬(타임존) 기준 1일 1회 발화 시각. 기본 04:30 (장 개장 전 배치 윈도우).
    run_at_local                time NOT NULL DEFAULT '04:30',
    timezone                    text NOT NULL DEFAULT 'Asia/Seoul',
    -- 수집 대상 소스 키 배열(예: ["price","dart"]). report 등 추후 추가 가능.
    targets                     jsonb NOT NULL DEFAULT '["price","dart"]'::jsonb,
    -- 소스별 파라미터.
    dart_limit                  integer NOT NULL DEFAULT 10,
    price_modes                 jsonb NOT NULL DEFAULT '["flows","snapshot"]'::jsonb,
    -- 실행 상태(스케줄러가 기록 → 어드민/MCP 가 조회).
    last_run_at                 timestamptz,
    last_status                 text,
    last_detail                 jsonb,
    next_run_at                 timestamptz,
    -- 어드민/MCP "지금 실행": 이 시각이 last_run_at 보다 최신이면 스케줄러가 즉시 발화.
    manual_trigger_requested_at timestamptz,
    -- 감사.
    updated_by                  text,
    updated_at                  timestamptz NOT NULL DEFAULT now()
);

-- 기본 스케줄 1행 시드(멱등). Kiwoom 가격 + DART, 매일 04:30 KST.
INSERT INTO public.collection_schedules (name, enabled, run_at_local, timezone, targets, dart_limit, price_modes)
VALUES ('daily-collection', true, '04:30', 'Asia/Seoul', '["price","dart"]'::jsonb, 10, '["flows","snapshot"]'::jsonb)
ON CONFLICT (name) DO NOTHING;

-- Grants (멱등, 롤 존재 시에만):
--   signal_backend : 어드민(main-server)이 config 읽고/쓰기 — 전체 DML.
--   signal_worker  : 워커측 스케줄러가 백엔드 연결로 config 읽고 상태(UPDATE) 기록.
-- 컷오버 전 dev 는 owner DSN 이라 grant 없이도 동작하지만, 롤 격리 발효 시를 위해 함께 부여.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_backend') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON public.collection_schedules TO signal_backend;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_worker') THEN
        GRANT SELECT, UPDATE ON public.collection_schedules TO signal_worker;
    END IF;
END $$;
