-- 20260707_1600_user_broker_credentials.sql
-- target: backend
-- ============================================================================
-- 매매 의사결정 부검 — 유저 증권사 API 자격증명 (spec: journal-postmortem-spec.md §3.3)
-- ----------------------------------------------------------------------------
-- 유저가 본인 키움/토스 앱키·시크릿을 입력하면 그 키로 계좌 체결내역을 조회한다(입력방식=
--   증권사 API 연동). 키는 주문권한까지 포함하는 민감정보라 **at-rest 암호화**(Fernet)해서
--   저장한다 — app_key_enc/app_secret_enc 는 암호문(bytea)이며 평문은 저장·반환·로그 어디에도
--   남기지 않는다(NFR-1). 복호는 워커 동기화 경로에서만(signal_worker), 등록·해제·조회는
--   main-server(signal_backend). 마스터키는 앱 env(BROKER_CRED_KEY) — DB에 없다.
-- 분류: backend DB(users 와 공존, db_partition BACKEND 등록). 체결 동기화·부검 산출은 후속.
-- ============================================================================

CREATE TABLE public.user_broker_credentials (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    broker          varchar(10) NOT NULL,
    -- 계좌 식별자(토스 X-Tossinvest-Account / 키움 계좌번호). 다계좌 분리 + upsert 자연키.
    -- 빈 문자열 = 단일/미지정 계좌. 민감도가 키만큼은 아니라 평문(조회 시 필요).
    account_ref     varchar(64) NOT NULL DEFAULT '',
    is_mock         boolean NOT NULL DEFAULT false,
    -- 암호문(Fernet 토큰). 평문 키는 여기에 절대 들어가지 않는다.
    app_key_enc     bytea NOT NULL,
    app_secret_enc  bytea NOT NULL,
    -- active: 정상 / error: 마지막 동기화 실패(키 만료 등) / revoked: 유저 해제 대기(soft)
    status          varchar(10) NOT NULL DEFAULT 'active',
    last_synced_at  timestamptz,
    last_error      text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_broker_cred_broker CHECK (broker IN ('kiwoom', 'toss')),
    CONSTRAINT chk_broker_cred_status CHECK (status IN ('active', 'error', 'revoked')),
    CONSTRAINT uq_broker_cred UNIQUE (user_id, broker, account_ref)
);

CREATE INDEX idx_broker_cred_user ON public.user_broker_credentials (user_id);

CREATE TRIGGER trg_broker_cred_updated_at
    BEFORE UPDATE ON public.user_broker_credentials
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- Grants (멱등, 롤 존재 시에만) --------------------------------------------
--   signal_backend : 등록/해제/조회(RW). 복호는 앱단 crypto 유틸(마스터키 env)로만.
--   signal_worker  : 동기화 시 자격증명 복호(SELECT) + 동기화 상태(UPDATE) 기록.
--                    INSERT/DELETE 는 백엔드 몫이라 부여하지 않는다.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_backend') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_broker_credentials TO signal_backend;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_worker') THEN
        GRANT SELECT, UPDATE ON public.user_broker_credentials TO signal_worker;
    END IF;
END $$;
