-- 20260702_1400_signal_journal_outcomes.sql
-- target: backend
-- ============================================================================
-- 저널 outcome 다중 시점(7/30 거래일) 확정 결과 테이블
-- ----------------------------------------------------------------------------
-- 배경: signal_journals 는 작성 시점 스냅샷만 보관하고, "그 후 실제 주가가 어떻게
--   됐나"(outcome)는 채우는 주체가 없었다. 일봉 종가(ohlcv_data)는 수집 DB 에만
--   있으므로 워커측 러너(run_journal_outcomes)가 BACKEND_DATABASE_URL 로 이 테이블에
--   확정 결과를 멱등 upsert 한다(collection_schedules 와 같은 워커→백엔드 계약).
-- 설계: 저널 원본(user_memo 등 유저 콘텐츠)에는 워커 쓰기 권한을 주지 않기 위해
--   별도 테이블로 분리. horizon 은 거래일 기준('7td','30td') — 캘린더는 해당 종목의
--   ohlcv trade_date 시계열 자체를 사용(휴장 자동 처리). UNIQUE(journal_id, horizon)
--   upsert 로 멱등. 저널 hard delete 시 함께 삭제(ON DELETE CASCADE).
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.signal_journal_outcomes (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_id         bigint NOT NULL REFERENCES public.signal_journals(id) ON DELETE CASCADE,
    horizon            varchar(10) NOT NULL,
    -- 작성일(KST) 이하 가장 최근 거래일과 그 종가(기준점).
    base_trade_date    date NOT NULL,
    base_price         numeric(12,2) NOT NULL,
    -- base 이후 N 번째 거래일과 그 종가(확정점).
    outcome_trade_date date NOT NULL,
    outcome_price      numeric(12,2) NOT NULL,
    change_pct         numeric(6,2) NOT NULL,
    checked_at         timestamptz NOT NULL DEFAULT now(),
    created_at         timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_journal_outcome_horizon CHECK (horizon IN ('7td', '30td')),
    CONSTRAINT uq_journal_outcome UNIQUE (journal_id, horizon)
);

CREATE INDEX IF NOT EXISTS idx_journal_outcomes_journal
    ON public.signal_journal_outcomes (journal_id);

-- Grants (멱등, 롤 존재 시에만):
--   signal_backend : API 응답 노출용 읽기 전용.
--   signal_worker  : outcome 러너가 확정 결과 기록(INSERT + upsert UPDATE).
--   signal_journals 는 워커에 컬럼 한정 SELECT 만 — 대상 저널 식별에 필요한
--   최소 컬럼(id, stock_id, created_at)만 노출하고 user_memo/tags 는 비노출.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_backend') THEN
        GRANT SELECT ON public.signal_journal_outcomes TO signal_backend;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'signal_worker') THEN
        GRANT SELECT, INSERT, UPDATE ON public.signal_journal_outcomes TO signal_worker;
        GRANT SELECT (id, stock_id, created_at) ON public.signal_journals TO signal_worker;
    END IF;
END $$;
